// pages/about.vue
<template>
  <div class="mt-4 flex justify-center">
    <h1 class="w-full text-center">
      About me
      <img
        class="profile-photo"
        src="/assets/images/avatar-small.jpg"
        alt="Danil Rodin"
        role="img"
        aria-label="Profile photo of Danil Rodin"
      />
    </h1>
  </div>

  <div class="mt-3 flex justify-center">
    <div class="about-card w-full md:w-9/12 lg:w-8/12">
      <h2>Nice to meet you!</h2>
      <p>
        I'm, <b>Danil Rodin</b>, the fullstack developer, father of two, GameDev enthusiast. Passionate at family,
        work, study and friendship. If you want to get in touch, feel free to reach out on telegram <NuxtLink to="https://t.me/casiq">@casiq</NuxtLink>.
      </p>

      <h2>My tech stack:</h2>
      <p><b>Backend:</b> laravel from v5 to latest, symfony v5, phalcon, NestJS</p>
      <p>
        <b>Frontend:</b> ES6, VueJS, vuex, pinia, vue-router, vuex-reststate, react, Svelte, Angular, Nuxt, React
        Native.
      </p>
      <p><b>DB:</b> MySQL, PostgreSQL, MongoDB, elasticsearch, redis.</p>
      <p><b>ENV:</b> linux based, docker, docker-compose, traefik, kuberenetes(k3s), terraform</p>
      <p><b>Methodologies:</b> agile, scrum, kanban</p>

      <p>Vegetarian. Health lifestyle. Sometimes I lift heavy weights in gym.</p>

    </div>
  </div>

  <div class="my-4 flex justify-center">
    <span class="w-full text-center">
      <NuxtLink to="/">Back to main page</NuxtLink>
    </span>
  </div>
</template>

<style scoped>
.about-card {
  color: #f4f4f4;
  line-height: 1.5;
  text-align: left;
}

.profile-photo {
  width: 220px;
  max-width: 100%;
  height: auto;
  border: 2px solid #d4ef99;
  display: flex;
  align-items: center;
  justify-content: center;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  margin: 0 auto 1.5rem auto;
  opacity: 0.7;
}
</style>

// src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['../app.component.less', './about.component.less']
})
export class AboutComponent implements OnInit {
  constructor(private title: Title, private meta: Meta) {}

  ngOnInit(): void {
    const ogImageUrl = `${window.location.origin}/assets/images/og-image.png`;
    this.title.setTitle('About me | Danil Rodin');
    this.meta.updateTag({
      name: 'description',
      content: 'Danil Rodin - fullstack developer, tech stack, background and personal profile.'
    });
    this.meta.updateTag({ property: 'og:title', content: 'About me | Danil Rodin' });
    this.meta.updateTag({
      property: 'og:description',
      content: 'Fullstack developer profile and tech stack.'
    });
    this.meta.updateTag({ property: 'og:image', content: ogImageUrl });
    this.meta.updateTag({ property: 'og:image:alt', content: 'Danil Rodin' });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ name: 'twitter:image', content: ogImageUrl });
  }
}

<div class="row mt-4">
  <span class="col"></span>
  <h1 class="col-12">About me
    <img
      class="profile-photo"
      src="assets/images/avatar-small.jpg"
      alt="Danil Rodin"
      role="img"
      aria-label="Profile photo of Danil Rodin"
    /></h1>
  <span class="col"></span>
</div>

<div class="row mt-3">
  <span class="col"></span>
  <div class="col-12 col-md-9 col-lg-8 about-card">


    <h2>Nice to meet you!</h2>
    <p>
      I'm, <b>Danil Rodin</b>, the fullstack developer, father of two, GameDev enthusiast.
      Passionate at family, work, study and friendship.
    </p>

    <h2>My tech stack:</h2>
    <p><b>Backend:</b> laravel from v5 to latest, symfony v5, phalcon, NestJS</p>
    <p>
      <b>Frontend:</b> ES6, VueJS, vuex, pinia, vue-router, vuex-reststate, react, Svelte,
      Angular, Nuxt, React Native.
    </p>
    <p><b>DB:</b> MySQL, PostgreSQL, MongoDB, elasticsearch, redis.</p>
    <p><b>ENV:</b> linux based, docker, docker-compose, traefik, kuberenetes(k3s), terraform</p>
    <p><b>Methodologies:</b> agile, scrum, kanban</p>

    <p>Vegetarian. Health lifestyle. Sometimes I lift heavy weights in gym.</p>
  </div>
  <span class="col"></span>
</div>

<div class="row mt-4">
  <span class="col"></span>
  <span class="col-12 text-center">
    <a routerLink="/">Back to main page</a>
  </span>
  <span class="col"></span>
</div>
