// src/app/projects/projects.component.ts
import { Component, OnInit } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['../app.component.less', './projects.component.less']
})
export class ProjectsComponent implements OnInit {
  constructor(private pageTitle: Title, private meta: Meta) {}

  ngOnInit(): void {
    const ogImageUrl = `${window.location.origin}/assets/images/og-image.png`;
    this.pageTitle.setTitle('Projects | Danil Rodin');
    this.meta.updateTag({
      name: 'description',
      content: 'Selected projects by Danil Rodin including game development and tooling work.'
    });
    this.meta.updateTag({ property: 'og:title', content: 'Projects | Danil Rodin' });
    this.meta.updateTag({
      property: 'og:description',
      content: 'Selected projects by Danil Rodin including game development and tooling work.'
    });
    this.meta.updateTag({ property: 'og:image', content: ogImageUrl });
    this.meta.updateTag({ property: 'og:image:alt', content: 'Danil Rodin' });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ name: 'twitter:image', content: ogImageUrl });
  }
}

<div class="row mt-4">
  <span class="col"></span>
  <h4 class="col-12">My projects:</h4>
  <span class="col"></span>
</div>
<div class="row mt-4">
  <span class="col"></span>
  <iframe
    src="https://itch.io/embed/2068346?linkback=true&amp;border_width=4&amp;bg_color=000000&amp;fg_color=ffffff&amp;link_color=327345&amp;border_color=d4ef99"
    width="558"
    height="173"
    frameborder="0"
    ><a href="https://casiq.itch.io/ctf"
      >Cosmic Tree Fighters by casiq</a
    ></iframe
  >
  <span class="col"></span>
</div>
<div class="row mt-4">
  <span class="col"></span
  ><span class="col"
    ><a
      href="https://marketplace.visualstudio.com/items?itemName=crewsycrews.bundlephobia-support"
      >BundlePhobia Vscode Extension</a
    >
  </span>
  <span class="col"></span>
</div>
<div class="row mt-4">
  <span class="col"></span>
  <span class="col-12 text-center">
    <a routerLink="/">Back to main page</a> |
    <a routerLink="/about">About me</a>
  </span>
  <span class="col"></span>
</div>

// pages/projects.vue
<template>
  <div class="mt-4 flex justify-center">
    <h4 class="w-full text-center">My projects:</h4>
  </div>
  <div class="mt-4 flex justify-center">
    <iframe
      src="https://itch.io/embed/2068346?linkback=true&amp;border_width=4&amp;bg_color=000000&amp;fg_color=ffffff&amp;link_color=327345&amp;border_color=d4ef99"
      width="558"
      height="173"
      frameborder="0"
      ></iframe
    >
  </div>
  <div class="mt-4 flex justify-center">
    <span class="w-full text-center"
      ><a
        href="https://marketplace.visualstudio.com/items?itemName=crewsycrews.bundlephobia-support"
        target="_blank"
        rel="noopener noreferrer"
        >BundlePhobia VS Code extension on Visual Studio Marketplace</a
      >
    </span>
  </div>
  <div class="mt-4 flex justify-center">
    <span class="w-full text-center">
      <NuxtLink to="/">Back to main page</NuxtLink> |
      <NuxtLink to="/about">About me</NuxtLink>
    </span>
  </div>
</template>
